"""Report generator for audit framework."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from .validator import Finding, Severity


def generate_markdown_report(
    findings: list[Finding],
    formulas_audited: int,
    target_name: str = "Audit",
    output_path: str | Path | None = None,
) -> str:
    """Generate a markdown audit report."""
    from .validator import categorize_findings
    
    categorized = categorize_findings(findings)
    timestamp = datetime.now().isoformat()
    
    lines = [
        f"# {target_name} Audit Report",
        "",
        f"**Generated:** {timestamp}",
        f"**Formulas Audited:** {formulas_audited}",
        f"**Total Findings:** {len(findings)}",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    
    for severity in ["critical", "high", "medium", "low", "info"]:
        count = len(categorized.get(severity, []))
        lines.append(f"| {severity.upper()} | {count} |")
    
    lines.extend(["", "## Critical Findings", ""])
    
    if categorized["critical"]:
        for finding in categorized["critical"]:
            lines.extend(format_finding(finding))
    else:
        lines.append("*No critical findings.*")
    
    lines.extend(["", "## High Severity Findings", ""])
    
    if categorized["high"]:
        for finding in categorized["high"]:
            lines.extend(format_finding(finding))
    else:
        lines.append("*No high severity findings.*")
    
    lines.extend(["", "## Medium Severity Findings", ""])
    
    if categorized["medium"]:
        for finding in categorized["medium"]:
            lines.extend(format_finding(finding))
    else:
        lines.append("*No medium severity findings.*")
    
    lines.extend(["", "## Low Severity Findings", ""])
    
    if categorized["low"]:
        for finding in categorized["low"]:
            lines.extend(format_finding(finding))
    else:
        lines.append("*No low severity findings.*")
    
    lines.extend(["", "## Informational", ""])
    
    if categorized["info"]:
        for finding in categorized["info"]:
            lines.extend(format_finding(finding))
    else:
        lines.append("*No informational findings.*")
    
    lines.extend([
        "",
        "## Recommendations",
        "",
        "1. **Address critical findings immediately** - these may cause formula execution failures",
        "2. **Fix high severity issues** - these affect formula correctness or clarity",
        "3. **Review medium severity items** - these improve formula quality",
        "4. **Consider low/info suggestions** - these are best practices",
        "",
        "---",
        "",
        f"*Report generated by lora_forge audit framework*",
    ])
    
    report = "\n".join(lines)
    
    if output_path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(report)
    
    return report


def format_finding(finding: Finding) -> list[str]:
    """Format a single finding for markdown."""
    lines = [
        f"### {finding.issue}",
        "",
        f"- **Formula:** `{finding.formula}`",
        f"- **Location:** `{finding.location}`",
        f"- **Category:** {finding.category}",
        f"- **Recommendation:** {finding.recommendation}",
        "",
    ]
    
    if finding.details:
        lines.append("**Details:**")
        lines.append("```json")
        lines.append(json.dumps(finding.details, indent=2))
        lines.append("```")
        lines.append("")
    
    return lines


def generate_json_report(
    findings: list[Finding],
    formulas_audited: int,
    target_name: str = "Audit",
    output_path: str | Path | None = None,
) -> dict[str, Any]:
    """Generate a JSON audit report."""
    from .validator import categorize_findings
    
    categorized = categorize_findings(findings)
    timestamp = datetime.now().isoformat()
    
    report = {
        "metadata": {
            "generated": timestamp,
            "target": target_name,
            "formulas_audited": formulas_audited,
            "total_findings": len(findings),
        },
        "summary": {
            severity: len(findings_list)
            for severity, findings_list in categorized.items()
        },
        "findings": [finding.to_dict() for finding in findings],
        "categorized": {
            severity: [f.to_dict() for f in findings_list]
            for severity, findings_list in categorized.items()
        },
    }
    
    if output_path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(report, f, indent=2)
    
    return report


def generate_summary(findings: list[Finding]) -> str:
    """Generate a brief summary of findings."""
    from .validator import categorize_findings
    
    categorized = categorize_findings(findings)
    
    summary_parts = []
    for severity in ["critical", "high", "medium", "low", "info"]:
        count = len(categorized.get(severity, []))
        if count > 0:
            summary_parts.append(f"{count} {severity}")
    
    if not summary_parts:
        return "No findings"
    
    return ", ".join(summary_parts)


if __name__ == "__main__":
    import sys
    from extractor import extract_all_formulas
    from validator import validate_all
    
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    formulas = extract_all_formulas(base)
    findings = validate_all(formulas)
    
    md_report = generate_markdown_report(findings, len(formulas), "Test Audit")
    print(md_report)
